// Generated by scripts/promo-screens/capture.mjs — do not edit by hand.
export default {
  "viewport": {
    "width": 390,
    "height": 800
  },
  "scale": 3,
  "screens": {
    "home": "home.webp",
    "list": "list.webp",
    "search_0": "search_0.webp",
    "search_1": "search_1.webp",
    "search_2": "search_2.webp",
    "search_3": "search_3.webp",
    "search_4": "search_4.webp",
    "voucher": "voucher.webp",
    "use_0": "use_0.webp",
    "use_8": "use_8.webp",
    "use_80": "use_80.webp",
    "voucher_after": "voucher_after.webp",
    "list_after": "list_after.webp",
    "home_after": "home_after.webp"
  },
  "top": {
    "home": "#f2f4f3",
    "list": "#ffffff",
    "search_0": "#ffffff",
    "search_1": "#ffffff",
    "search_2": "#ffffff",
    "search_3": "#ffffff",
    "search_4": "#ffffff",
    "voucher": "#e44091",
    "use_0": "#f1f3f2",
    "use_8": "#f1f3f2",
    "use_80": "#f1f3f2",
    "voucher_after": "#e44091",
    "list_after": "#ffffff",
    "home_after": "#f2f4f3"
  },
  "boxes": {
    "nav_vouchers": {
      "x": 252.359375,
      "y": 753,
      "w": 38,
      "h": 16
    },
    "list_zara_balance": {
      "x": 25,
      "y": 202,
      "w": 68,
      "h": 32
    },
    "list_zara_expiry": {
      "x": 271,
      "y": 248,
      "w": 86,
      "h": 24
    },
    "list_fox_expiry": {
      "x": 260.234375,
      "y": 375,
      "w": 96.765625,
      "h": 24
    },
    "search_input": {
      "x": 30,
      "y": 60,
      "w": 300,
      "h": 52
    },
    "search_zara_card": {
      "x": 257,
      "y": 234,
      "w": 42,
      "h": 24
    },
    "voucher_code": {
      "x": 75,
      "y": 276,
      "w": 240,
      "h": 240
    },
    "voucher_codeText": {
      "x": 106.984375,
      "y": 520,
      "w": 176.03125,
      "h": 35
    },
    "voucher_balance": {
      "x": 166,
      "y": 79.5,
      "w": 130,
      "h": 56
    },
    "voucher_fab": {
      "x": 16,
      "y": 640,
      "w": 358,
      "h": 60
    },
    "use_amount": {
      "x": 30,
      "y": 443.5,
      "w": 330,
      "h": 50
    },
    "use_fab": {
      "x": 16,
      "y": 640,
      "w": 358,
      "h": 60
    },
    "after_balance": {
      "x": 166,
      "y": 79.5,
      "w": 130,
      "h": 56
    },
    "list_after_fox_expiry": {
      "x": 260.234375,
      "y": 390,
      "w": 96.765625,
      "h": 24
    }
  }
} as const
